// Icon for each block type, shared by canvas nodes and the palette.

import {
  Activity,
  ArrowDownToLine,
  ArrowRightLeft,
  BellRing,
  Box,
  CircleDot,
  Crosshair,
  GitBranch,
  Grab,
  Hand,
  Hourglass,
  House,
  LayoutGrid,
  LocateFixed,
  MapPin,
  MessageSquareText,
  Move,
  Play,
  Repeat,
  Repeat2,
  RotateCw,
  ScanEye,
  Send,
  Square,
  SquarePlus,
  Timer,
  ToggleRight,
  Variable,
  type LucideIcon,
} from 'lucide-react';

const ICONS: Record<string, LucideIcon> = {
  start: Play,
  end: Square,
  if: GitBranch,
  for: Repeat,
  while: Repeat2,
  wait_until: Hourglass,
  delay: Timer,
  alarm: BellRing,
  move_pose: MapPin,
  move_position: Crosshair,
  move_relative: Move,
  move_joint: RotateCw,
  home: House,
  get_position: LocateFixed,
  pick: Hand,
  place: ArrowDownToLine,
  gripper: Grab,
  conveyor: ArrowRightLeft,
  set_output: ToggleRight,
  wait_input: CircleDot,
  inspect: ScanEye,
  read_input: Activity,
  set_var: Variable,
  change_var: SquarePlus,
  pallet: LayoutGrid,
  log: MessageSquareText,
  mqtt_publish: Send,
};

export function blockIcon(type: string): LucideIcon {
  return ICONS[type] ?? Box;
}
